[ pid=17001 thr=398660 file=utils.rb:176 time=2010-11-23 00:55:31.781 ]: *** Exception LoadError in PhusionPassenger::Rack::ApplicationSpawner (no such file to load -- rack) (process 17001, thread #<Thread:0x0c2a88>):
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/rack/application_spawner.rb:219:in `require'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/rack/application_spawner.rb:219:in `load_rack_app'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/rack/application_spawner.rb:156:in `block in initialize_server'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/utils.rb:564:in `report_app_init_status'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/rack/application_spawner.rb:153:in `initialize_server'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server.rb:204:in `start_synchronously'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server.rb:180:in `start'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/rack/application_spawner.rb:128:in `start'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/spawn_manager.rb:253:in `block (2 levels) in spawn_rack_application'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/spawn_manager.rb:246:in `block in spawn_rack_application'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server_collection.rb:82:in `block in synchronize'
	from <internal:prelude>:10:in `synchronize'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/spawn_manager.rb:244:in `spawn_rack_application'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/spawn_manager.rb:137:in `spawn_application'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/helper-scripts/passenger-spawn-server:99:in `<main>'
[ pid=17021 thr=398660 file=utils.rb:176 time=2010-11-23 00:56:39.910 ]: *** Exception LoadError in PhusionPassenger::Rack::ApplicationSpawner (no such file to load -- rack) (process 17021, thread #<Thread:0x0c2a88>):
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/rack/application_spawner.rb:219:in `require'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/rack/application_spawner.rb:219:in `load_rack_app'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/rack/application_spawner.rb:156:in `block in initialize_server'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/utils.rb:564:in `report_app_init_status'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/rack/application_spawner.rb:153:in `initialize_server'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server.rb:204:in `start_synchronously'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server.rb:180:in `start'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/rack/application_spawner.rb:128:in `start'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/spawn_manager.rb:253:in `block (2 levels) in spawn_rack_application'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/spawn_manager.rb:246:in `block in spawn_rack_application'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server_collection.rb:82:in `block in synchronize'
	from <internal:prelude>:10:in `synchronize'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/spawn_manager.rb:244:in `spawn_rack_application'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/spawn_manager.rb:137:in `spawn_application'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/helper-scripts/passenger-spawn-server:99:in `<main>'
[ pid=17062 thr=398660 file=utils.rb:176 time=2010-11-23 01:02:02.975 ]: *** Exception LoadError in PhusionPassenger::Rack::ApplicationSpawner (no such file to load -- rack) (process 17062, thread #<Thread:0x0c2a88>):
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/rack/application_spawner.rb:219:in `require'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/rack/application_spawner.rb:219:in `load_rack_app'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/rack/application_spawner.rb:156:in `block in initialize_server'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/utils.rb:564:in `report_app_init_status'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/rack/application_spawner.rb:153:in `initialize_server'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server.rb:204:in `start_synchronously'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server.rb:180:in `start'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/rack/application_spawner.rb:128:in `start'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/spawn_manager.rb:253:in `block (2 levels) in spawn_rack_application'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/spawn_manager.rb:246:in `block in spawn_rack_application'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server_collection.rb:82:in `block in synchronize'
	from <internal:prelude>:10:in `synchronize'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/spawn_manager.rb:244:in `spawn_rack_application'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/spawn_manager.rb:137:in `spawn_application'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/helper-scripts/passenger-spawn-server:99:in `<main>'
[ pid=17079 thr=398660 file=utils.rb:176 time=2010-11-23 01:03:37.610 ]: *** Exception LoadError in PhusionPassenger::Rack::ApplicationSpawner (no such file to load -- rack) (process 17079, thread #<Thread:0x0c2a88>):
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/rack/application_spawner.rb:219:in `require'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/rack/application_spawner.rb:219:in `load_rack_app'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/rack/application_spawner.rb:156:in `block in initialize_server'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/utils.rb:564:in `report_app_init_status'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/rack/application_spawner.rb:153:in `initialize_server'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server.rb:204:in `start_synchronously'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server.rb:180:in `start'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/rack/application_spawner.rb:128:in `start'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/spawn_manager.rb:253:in `block (2 levels) in spawn_rack_application'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/spawn_manager.rb:246:in `block in spawn_rack_application'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server_collection.rb:82:in `block in synchronize'
	from <internal:prelude>:10:in `synchronize'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/spawn_manager.rb:244:in `spawn_rack_application'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/spawn_manager.rb:137:in `spawn_application'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/helper-scripts/passenger-spawn-server:99:in `<main>'
[ pid=17129 thr=398660 file=utils.rb:176 time=2010-11-23 01:12:00.269 ]: *** Exception LoadError in PhusionPassenger::Rack::ApplicationSpawner (no such file to load -- rack) (process 17129, thread #<Thread:0x0c2a88>):
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/rack/application_spawner.rb:219:in `require'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/rack/application_spawner.rb:219:in `load_rack_app'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/rack/application_spawner.rb:156:in `block in initialize_server'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/utils.rb:564:in `report_app_init_status'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/rack/application_spawner.rb:153:in `initialize_server'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server.rb:204:in `start_synchronously'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server.rb:180:in `start'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/rack/application_spawner.rb:128:in `start'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/spawn_manager.rb:253:in `block (2 levels) in spawn_rack_application'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/spawn_manager.rb:246:in `block in spawn_rack_application'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server_collection.rb:82:in `block in synchronize'
	from <internal:prelude>:10:in `synchronize'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/spawn_manager.rb:244:in `spawn_rack_application'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/spawn_manager.rb:137:in `spawn_application'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
	from /Users/dagi3d/.passenger/standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/helper-scripts/passenger-spawn-server:99:in `<main>'
[ pid=23317 thr=398660 file=utils.rb:176 time=2010-11-23 01:16:12.164 ]: *** Exception LoadError in PhusionPassenger::Rack::ApplicationSpawner (no such file to load -- rack) (process 23317, thread #<Thread:0x0c2a88>):
	from /var/lib/passenger-standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/rack/application_spawner.rb:219:in `require'
	from /var/lib/passenger-standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/rack/application_spawner.rb:219:in `load_rack_app'
	from /var/lib/passenger-standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/rack/application_spawner.rb:156:in `block in initialize_server'
	from /var/lib/passenger-standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/utils.rb:564:in `report_app_init_status'
	from /var/lib/passenger-standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/rack/application_spawner.rb:153:in `initialize_server'
	from /var/lib/passenger-standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server.rb:204:in `start_synchronously'
	from /var/lib/passenger-standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server.rb:180:in `start'
	from /var/lib/passenger-standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/rack/application_spawner.rb:128:in `start'
	from /var/lib/passenger-standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/spawn_manager.rb:253:in `block (2 levels) in spawn_rack_application'
	from /var/lib/passenger-standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
	from /var/lib/passenger-standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/spawn_manager.rb:246:in `block in spawn_rack_application'
	from /var/lib/passenger-standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server_collection.rb:82:in `block in synchronize'
	from <internal:prelude>:10:in `synchronize'
	from /var/lib/passenger-standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
	from /var/lib/passenger-standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/spawn_manager.rb:244:in `spawn_rack_application'
	from /var/lib/passenger-standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/spawn_manager.rb:137:in `spawn_application'
	from /var/lib/passenger-standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
	from /var/lib/passenger-standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
	from /var/lib/passenger-standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
	from /var/lib/passenger-standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/helper-scripts/passenger-spawn-server:99:in `<main>'
[ pid=23510 thr=398660 file=utils.rb:176 time=2010-11-23 01:21:39.238 ]: *** Exception LoadError in PhusionPassenger::Rack::ApplicationSpawner (no such file to load -- rack) (process 23510, thread #<Thread:0x0c2a88>):
	from /var/lib/passenger-standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/rack/application_spawner.rb:219:in `require'
	from /var/lib/passenger-standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/rack/application_spawner.rb:219:in `load_rack_app'
	from /var/lib/passenger-standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/rack/application_spawner.rb:156:in `block in initialize_server'
	from /var/lib/passenger-standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/utils.rb:564:in `report_app_init_status'
	from /var/lib/passenger-standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/rack/application_spawner.rb:153:in `initialize_server'
	from /var/lib/passenger-standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server.rb:204:in `start_synchronously'
	from /var/lib/passenger-standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server.rb:180:in `start'
	from /var/lib/passenger-standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/rack/application_spawner.rb:128:in `start'
	from /var/lib/passenger-standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/spawn_manager.rb:253:in `block (2 levels) in spawn_rack_application'
	from /var/lib/passenger-standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
	from /var/lib/passenger-standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/spawn_manager.rb:246:in `block in spawn_rack_application'
	from /var/lib/passenger-standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server_collection.rb:82:in `block in synchronize'
	from <internal:prelude>:10:in `synchronize'
	from /var/lib/passenger-standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
	from /var/lib/passenger-standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/spawn_manager.rb:244:in `spawn_rack_application'
	from /var/lib/passenger-standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/spawn_manager.rb:137:in `spawn_application'
	from /var/lib/passenger-standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
	from /var/lib/passenger-standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
	from /var/lib/passenger-standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
	from /var/lib/passenger-standalone/3.0.0-i386-ruby1.9.2-x86_64-macosx-10.5/support/helper-scripts/passenger-spawn-server:99:in `<main>'
